LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := Launcher3
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS := APPS
LOCAL_PACKAGE_NAME := Launcher
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_SRC_FILES := launcher3.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES := Home Launcher2
LOCAL_MULTILIB := 64
  
include $(BUILD_PREBUILT)
